-- Migration 003: Add tags system for US 2.3
-- This migration adds proper tag management and study assignment functionality

-- Create tags table for centralized tag management
CREATE TABLE tags (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    description TEXT,
    status VARCHAR(20) DEFAULT 'approved' CHECK (status IN ('pending', 'approved', 'rejected')),
    created_by INTEGER REFERENCES users(id),
    approved_by INTEGER REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMP
);

-- Create artifact_tags junction table for many-to-many relationship
CREATE TABLE artifact_tags (
    id SERIAL PRIMARY KEY,
    artifact_id INTEGER REFERENCES artifacts(id) ON DELETE CASCADE,
    tag_id INTEGER REFERENCES tags(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(artifact_id, tag_id)
);

-- Add indexes for performance
CREATE INDEX idx_tags_name ON tags(name);
CREATE INDEX idx_tags_status ON tags(status);
CREATE INDEX idx_artifact_tags_artifact ON artifact_tags(artifact_id);
CREATE INDEX idx_artifact_tags_tag ON artifact_tags(tag_id);

-- Insert some default approved tags
INSERT INTO tags (name, description, status, approved_at) VALUES
('java', 'Java programming language', 'approved', CURRENT_TIMESTAMP),
('python', 'Python programming language', 'approved', CURRENT_TIMESTAMP),
('javascript', 'JavaScript programming language', 'approved', CURRENT_TIMESTAMP),
('algorithm', 'Algorithm implementation', 'approved', CURRENT_TIMESTAMP),
('data-structure', 'Data structure implementation', 'approved', CURRENT_TIMESTAMP),
('web-development', 'Web development related', 'approved', CURRENT_TIMESTAMP),
('mobile', 'Mobile application development', 'approved', CURRENT_TIMESTAMP),
('testing', 'Testing and quality assurance', 'approved', CURRENT_TIMESTAMP),
('documentation', 'Documentation and specifications', 'approved', CURRENT_TIMESTAMP),
('ui-ux', 'User interface and user experience', 'approved', CURRENT_TIMESTAMP),
('ai-generated', 'Content generated by artificial intelligence', 'approved', CURRENT_TIMESTAMP);